#ifndef UHBADGE_CYW43_PINS_H
    #define UHBADGE_CYW43_PINS_H

    #include "firmware.h"

    #define CYW43_PIN_WL_REG_ON GPIO_PI_RADIO_MODULE_WLON_BTON
    #define CYW43_PIN_WL_CS GPIO_PI_RADIO_MODULE_CS
    #define CYW43_PIN_WL_CLOCK GPIO_PI_RADIO_MODULE_SCLK
    #define CYW43_PIN_WL_D GPIO_PI_RADIO_MODULE_DI_DO_NIRQ
    #define CYW43_PIN_WL_HOST_WAKE GPIO_PI_RADIO_MODULE_DI_DO_NIRQ

    #define CYW43_USE_SPI 1
    #define CYW43_LWIP 1
#endif
